### ISSUE TITLE
Summary window

### ISSUE THREAD

**Issue by cfinke** [cfinke/Feed-Sidebar#16]
Would like an option for the summary window:  default (current behavior),
always on, or always off.

I just find it kind of annoying for that window to be constantly opening
and closing.
- Owner: [cfinke](http://code.google.com/u/cfinke/)

---

Issue imported from Google Code
Author: [cfinke](http://code.google.com/u/cfinke/)
Published: 2009-04-03T19:00:07.000Z
Status: Accepted
Link: http://code.google.com/p/feedsidebar/issues/detail?id=17

**Comment by MrLozzy** [comment]
People should note that it is possible to shrink the summary box all the way to the bottom, which essentially disables it. At least that's how I'd deal with it.

**Comment by cfinke** [comment]
Yep, just drag the summary box all the way down to disable it.
