### ISSUE TITLE
Feed Sidebar toolbar icon is huge

### ISSUE THREAD

**Issue by ksdixon** [cfinke/Feed-Sidebar#84]
I am using FireFox, and have the Feed Sidebar icon in my Navigation Toolbar, which uses normal images - or more specifically is not set to 'use small icons' in the customize/toolbar layout menu.

I have no problems with the addon's functionality other than the icon appears to be HUGE when placed on the navigation menu and does not 'use small icons'. 

Image 1: http://img819.imageshack.us/img819/8518/i88o.png
Image 2: http://img94.imageshack.us/img94/1809/y6vl.png

Is there a way to fix this? 

Also, could you perhaps give a choice of which icon to use, between the two we have for now for new/no new feed items, and two new ones which are grey to better fit-in with the look of FF's other buttons?

**Comment by cfinke** [comment]
This has been fixed in Firefox's new Australis design, coming in version 29.

**Comment by Keith94** [comment]
@cfinke Feed Sidebar's widget is still too large even in Firefox 31. It's two pixels taller than the other default widgets, and it increases the overall height of the nav-bar by 2px also.
