### ISSUE TITLE
Feed Sidebar menuitem acceltext still says Ctrl+Shift+F

### ISSUE THREAD

**Issue by Quicksaver** [cfinke/Feed-Sidebar#87]
It still says Ctrl+Shift+F in all locales, which is wrong since you changed it to Y. BTW, I was going to create a pull but I saw that you had a double keyset element, one for the F accesskey in the dtd, and another that always overrides it with a hardcoded Y, and got confused so I thought it was better to leave it alone.

**Comment by Quicksaver** [comment]
And it also says that on OSX, maybe it should say "⇧⌘Y" instead (copy-paste'ing that to a dtd entity or directly to the acceltext attribute works fine btw).

**Comment by cfinke** [comment]
Thanks for the feedback; I've fixed it and am uploading the change as 8.0.4.
